### ISSUE TITLE
Travis should automatically deploy to Firebase after successful build

### ISSUE THREAD

**Issue by mschilling** [mschilling/crossover#4]
After a successful Travis build, the app (PWA) should automatically be deployed to Firebase Hosting.

Pre-condition: only run firebase deploy in `master` branch.

**Comment by mschilling** [comment]
@cassshh I know, you have already established to run an automatic deploy to Firebase. Next up: check for condition `current_branch == 'master'` ..

**Comment by mschilling** [comment]
Useful resource https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

**Comment by cassshh** [comment]
Resolved in a067283

Only deploy if:
- Build is successful
- Branch is master
- Not a PR
